// Desk Item icons (spec 7.2): one unique 14x14 (+outline) icon per item. Hand-authored ASCII pixel art.
import type { IDef } from './gfx';
import { build } from './gfx';

export const DESK_ICONS: Record<string, IDef> = {
  stress_ball: { rows: [
    '....OOOOOO....',
    '..OOoooOOOOO..',
    '.OOooOOOOOOOn.',
    '.OoOOOOOOOOOn.',
    'OOoOOOOOOOOOOn',
    'OOOOOOOnOOOOOn',
    'OOOOOOnnOOOOOn',
    'OOOOOnOOOOOOnn',
    '.OOOnOOOOOOnn.',
    '.OOOOOOOOOnnn.',
    '..nOOOOOOnnn..',
    '....nnnnnn....',
  ] },
  out_of_office: { rows: [
    '.........lll..',
    '..........l...',
    '.........lll..',
    '.wWWWWWWWWWV..',
    '.WVWWWWWWWVV..',
    '.WWVWWWWWVWV..',
    '.WWWVVVVVWWV..',
    '.WGGGWWWWWWV..',
    '.WWGGGGGWWWV..',
    '.WGGGWWWWWWV..',
    '.VVVVVVVVVVv..',
  ] },
  company_card: { rows: [
    '..............',
    '.dddddddddddd.',
    '.dYyyyyyyyyud.',
    '.dYYYYYYYYYud.',
    '.dYYddYYYYYud.',
    '.dYYddYYYYYud.',
    '.dYYYYYYYYYud.',
    '.deeeeeeeeeed.',
    '.dYYYYYYYYYud.',
    '.dYYwwYYwwYud.',
    '.dddddddddddd.',
  ], pal: { d: '#2a2f3b' } },
  gold_lanyard: { rows: [
    '.Y..........Y.',
    '.YY........YY.',
    '..YY......YY..',
    '...YY....YY...',
    '....YYYYYY....',
    '.....YYYY.....',
    '.....bbbb.....',
    '....bwaabb....',
    '....WWWWWV....',
    '....WYYYWV....',
    '....WWWWWV....',
    '....VVVVVv....',
  ] },
  employee_handbook: { rows: [
    '..............',
    '.jjjjjjjjjjj..',
    '.jBBBBBBBBBj..',
    '.jBlBBBBBBBjW.',
    '.jBBBYYYBBBjW.',
    '.jBBYyYYYBBjW.',
    '.jBBBYYYBBBjW.',
    '.jBBBBBBBBBjW.',
    '.jBWWWWWWBBjW.',
    '.jBWVVVVWBBjW.',
    '.jBBBBBBBBBjV.',
    '.jjjjjjjjjjjv.',
  ] },
  ergonomic_cushion: { rows: [
    '..............',
    '.zZZZZZZZZZZ..',
    'zZZZZZZZZZZZZ.',
    'ZZZZZZZZZZZZZQ',
    'ZZZZZZZdZZZZZQ',
    'ZZZZZZdQdZZZZQ',
    'ZZZZZZZdZZZZZQ',
    'ZZZZZZZZZZZZZQ',
    '.ZZZZZZZZZZZQ.',
    '..QQQQQQQQQQ..',
  ] },
  lucky_mug: { rows: [
    '.....s.s......',
    '......s.s.....',
    '..WWWWWWWWV...',
    '..WWWWWWWWVbb.',
    '..WWGGWGGWVb.b',
    '..WWGGGGGWVb.b',
    '..WWWGGGWWVb.b',
    '..WWGGWGGWVb.b',
    '..WWWWWWWWVbb.',
    '...VVVVVVVV...',
  ] },
  noise_cancelling: { rows: [
    '....dddddd....',
    '..dd......dd..',
    '.dd........dd.',
    '.d..........d.',
    'ddd........ddd',
    'dccd......dccd',
    'dcccd....dcccd',
    'dcbcd....dcbcd',
    'dcccd....dcccd',
    'dccd......dccd',
    '.dd........dd.',
  ], pal: { d: '#2a2f3b' } },
  standing_desk: { rows: [
    '......Y.......',
    '.....YYY......',
    '....YYYYY.....',
    '......Y.......',
    '.TTTTTTTTTTTT.',
    '.tTTTTTTTTTTm.',
    '.mmmmmmmmmmmm.',
    '..cb......bc..',
    '..cb......bc..',
    '..cb......bc..',
    '..cb......bc..',
    '.dccd....dccd.',
  ] },
  fidget_spinner: { rows: build(14, 14, (p, rc, dc, ln) => {
    ln(7, 7, 7, 3, 'j', 2); ln(7, 7, 3, 10, 'j', 2); ln(7, 7, 10, 10, 'j', 2);
    dc(7.5, 3.5, 3, 'B'); dc(3.5, 10, 3, 'B'); dc(10.5, 10, 3, 'B');
    dc(7.5, 3.5, 1.4, 'e'); dc(3.5, 10, 1.4, 'e'); dc(10.5, 10, 1.4, 'e');
    dc(7, 7, 2.2, 'l'); dc(7, 7, 1.2, 'a'); p(6, 6, 'w'); p(6, 2, 'l'); p(2, 9, 'l'); p(9, 9, 'l');
  }) },
  desk_fan: { rows: [
    '....bbbbbb....',
    '..bbaaaaaabb..',
    '.baaBaaaaBaab.',
    '.baBBBaaBBBab.',
    'baaaBBBBBBaaab',
    'baaaaBddBaaaab',
    'baaaaBddBaaaab',
    'baaaBBBBBBaaab',
    '.baBBBaaBBBab.',
    '.baaBaaaaBaab.',
    '..bbaaaaaabb..',
    '....bbbbbb....',
    '.....cddc.....',
  ] },
  post_it_notes: { rows: [
    '..............',
    '..yyyyyyyyyy..',
    '.yYYYYYYYYYYu.',
    '.YYuuuuuuuuYu.',
    '.YYYYYYYYYYYu.',
    '.YuuuuuuuYYYu.',
    '.YYYYYYYYYYYu.',
    '.YuuuuuuuuYYu.',
    '.YYYYYYYYYYYu.',
    '.YYYYYYYYYYYuu',
    '.YYYYYYYYYYuyu',
    '..uuuuuuuuuu..',
  ], pal: { y: '#fbe97a', Y: '#f4d84a', u: '#c9a92a' } },
  duct_tape: { rows: [
    '....bbbbbb....',
    '..bbaaaaaabb..',
    '.baaccccccaab.',
    '.bacc....ccab.',
    'bacc......ccab',
    'bac........cab',
    'bac........cab',
    'bacc......ccab',
    '.bacc....ccab.',
    '.bbcccccccbbb.',
    '..bbbbbbbbbb..',
    '..............',
  ] },
  lanyard_clip: { rows: [
    '.....bbbb.....',
    '....bwaabb....',
    '...bc....cb...',
    '...bc....cb...',
    '..dddddddddd..',
    '..dcccbbcccd..',
    '..dcb.BB.bcd..',
    '..dcb.BB.bcd..',
    '..dcccbbcccd..',
    '..dddddddddd..',
    '.....cc.......',
    '.....cc.......',
    '....bbbb......',
  ] },
  swear_jar: { rows: [
    '...dddddddd...',
    '...baaaaaab...',
    '..bwllllllab..',
    '.bwlllllllllb.',
    '.blllRRlRRlWb.',
    '.blllRlRlRlWb.',
    '.blllllllllWb.',
    '.blYYllYYllWb.',
    '.blYYYYYYYYWb.',
    '.blYYYYYYYYWb.',
    '..bllllllllb..',
    '...bbbbbbbb...',
  ] },
  hang_in_there: { rows: [
    '.mmmmmmmmmmmm.',
    '.mWWWWWWWWWWm.',
    '.mWNNNNNNNNWm.',
    '.mWWWWOOWWWWm.',
    '.mWWWOOOOWWWm.',
    '.mWWWOnnOWWWm.',
    '.mWWWWOOWWWWm.',
    '.mWWWWOnWWWWm.',
    '.mWWWWOOWWWWm.',
    '.mWWWWWWWWWWm.',
    '.mmmmmmmmmmmm.',
  ] },
  desk_plant: { rows: [
    '...g..g.......',
    '..gGg.Gg.g....',
    '.gGGGgGGgGg...',
    '..GGGhGGGGh...',
    '...hGGhGGh....',
    '....hGGGh.....',
    '..oOOOOOOOn...',
    '..OOOOOOOOn...',
    '...OOOOOOn....',
    '...OOOOOOn....',
    '....nnnnn.....',
  ] },
  calculator_watch: { rows: [
    '....dddddd....',
    '....dccccd....',
    '...dddddddd...',
    '..dccccccccd..',
    '..dcGggGGGcd..',
    '..dcGGGGGGcd..',
    '..dcacacacdd..',
    '..dcacacacdd..',
    '..dccccccccd..',
    '...dddddddd...',
    '....dccccd....',
    '....dddddd....',
  ] },
  monogrammed_stapler: { rows: [
    '..............',
    '......rrrrrrr.',
    '....rrRRRRRRR.',
    '...rRRRRYYRRR.',
    '..bbddddYuddd.',
    '.bacdcccccccc.',
    '.dddeeeeeeee..',
    '..qRRRRRRRq...',
    '..qqqqqqqqq...',
  ] },
  suspicious_usb: { rows: build(14, 14, (p, rc) => {
    rc(0, 6, 5, 4, 'a'); rc(0, 6, 5, 1, 'w'); rc(0, 9, 5, 1, 'b'); p(1, 7, 'e'); p(1, 8, 'e'); p(3, 7, 'e'); p(3, 8, 'e');
    rc(5, 5, 8, 6, 'd'); rc(5, 5, 8, 1, 'c'); rc(5, 10, 8, 1, 'e'); rc(12, 5, 1, 6, 'e');
    rc(7, 7, 4, 3, 'W'); p(8, 7, 'e'); p(9, 7, 'e'); p(9, 8, 'e'); p(8, 9, 'e'); p(10, 8, 'W');
    p(12, 9, 'R');
    p(9, 0, 'y'); p(8, 1, 'y'); p(9, 2, 'y'); p(8, 3, 'y'); p(7, 3, 'Y'); p(10, 1, 'Y'); p(11, 2, 'y'); p(11, 3, 'Y');
  }) },
  coffee_loyalty: { rows: [
    '..............',
    '.NNNNNNNNNNNN.',
    '.NtttTTTTTTTm.',
    '.NtWWWWWWWWTm.',
    '.NtWRWRWRWWTm.',
    '.NtWWWWWWWWTm.',
    '.NtWRWRWWWWTm.',
    '.NtWWWWWWWWTm.',
    '.NTTTTTTTTTTm.',
    '.mmmmmmmmmmmm.',
  ] },
  spare_hi_vis: { rows: [
    '..OOO....OOO..',
    '.OOOOO..OOOOO.',
    '.OOOOOOOOOOOO.',
    'OOOOOOOOOOOOOO',
    'OOaaaaOOaaaaOO',
    'OObbbbOObbbbOO',
    'OOOOOOOOOOOOOn',
    'OOOOOOOOOOOOOn',
    '.OaaaaaaaaaaO.',
    '.ObbbbbbbbbbO.',
    '.OOOOOOOOOOOn.',
    '.nnnnnnnnnnnn.',
  ] },
  shredded_contract: { rows: [
    '..............',
    '.WWWWWWWWWWW..',
    '.WVVVVVVVVVW..',
    '.WWWWWWWWWWW..',
    '.WVVVVVVVWWW..',
    '.WWWWWWWWWWW..',
    '.W.W.W.W.W.W..',
    '.W.W.W.W.W.W..',
    '.V.V.V.V.V.V..',
    '.V..V.V..V.V..',
    '..V..V....V...',
  ] },
  fake_name_badge: { rows: [
    '.....bbbb.....',
    '.....bccb.....',
    '..RRRRRRRRRR..',
    '..RwwwwwwwwR..',
    '..RWWWWWWWWR..',
    '..RWWdddWWWR..',
    '..RWdWWWdWWR..',
    '..RWWWWdWWWR..',
    '..RWWWWWWWWR..',
    '..RWWWdWWWWR..',
    '..RRRRRRRRRR..',
  ] },
  double_booked: { rows: [
    '.bb........bb.',
    '.RRRRRRRRRRRR.',
    '.RrRRRRRRRRRq.',
    '.WWWWWWWWWWWV.',
    '.WBBBBBBWWWWV.',
    '.WBBBBBBBBGGV.',
    '.WWWWBBBBBGGV.',
    '.WWWWGGGGGGGV.',
    '.WWWWGGGGGWWV.',
    '.VVVVVVVVVVVv.',
  ] },
  cycle_helmet: { rows: [
    '....jjjjjj....',
    '..jjBlllBBjj..',
    '.jBBlBBBBBBBj.',
    '.jBjBjBjBjBBj.',
    'jBBjBjBjBjBBBj',
    'jBBBBBBBBBBBBj',
    'jjjjjjjjjjjjjj',
    '.ddd......ddd.',
    '.dcd......dcd.',
    '.dd........dd.',
  ] },
  golden_handshake: { rows: [
    '..............',
    '..............',
    'jjW........Wjj',
    'jjWyyYYYYuYWjj',
    'jjWyYYYYuYYWjj',
    'jjWYYYYuYYYWjj',
    'jjWYYYuYYYYWjj',
    'jjWYYuYYYYuWjj',
    'jjWYuYYYYuYWjj',
    'jjWuuYYYuYYWjj',
    'jjW........Wjj',
  ] },
  fudged_receipts: { rows: [
    '..wWWWWWWWV...',
    '..WWWWWWWWV...',
    '..WddddWddV...',
    '..WWWWWWWWV...',
    '..WdddddWWV...',
    '..WWWWWWWWV...',
    '..WddWdddWV...',
    '..WWWWWWWWV...',
    '..WRRRRRRWV...',
    '..WWWWWWWWV...',
    '..WVWVWVWVV...',
  ] },
  phone_charger: { rows: [
    '..............',
    '..bb..bb......',
    '..bb..bb......',
    '.dddddddd.....',
    '.dWWWWWWd.....',
    '.dWWWWWWd.....',
    '.dWWWWWWd.....',
    '.dVVVVVVd.....',
    '..dddddd......',
    '....dc........',
    '....dc........',
  ] },
  emergency_opener: { rows: [
    '.RRRRRRRRRRRR.',
    '.RWWWWWWWWWWq.',
    '.RWWWWWWWWaaq.',
    '.RWWWWWWWabbq.',
    '.RWWWWWWabcWq.',
    '.RWWWWWabcWWq.',
    '.RWWWYYbcWWWq.',
    '.RWWYyYuWWWWq.',
    '.RWWuYuWWWWWq.',
    '.RWWWWWWWWWWq.',
    '.qqqqqqqqqqqq.',
  ] },
  leave_request: { rows: [
    '..............',
    '.WWWWWWWWWWWV.',
    '.WGGGGGGGGGWV.',
    '.WWWWWWWWWWWV.',
    '.WYYWdddddWWV.',
    '.WYYWWWWWWWWV.',
    '.WWWWdddddWWV.',
    '.WGGWWWWWWWWV.',
    '.WGgWdddWWWWV.',
    '.WWWWWWWWWWWV.',
    '.VVVVVVVVVVVv.',
  ] },
  wrist_rest: { rows: [
    '..............',
    '.dddddddddddd.',
    '.dccccccccccd.',
    '.dcccccccccccd',
    '.dccBBBBBBccd.',
    '.dccBllBBBccd.',
    '.dccBBBBBBccd.',
    '.dccBBBBBBccd.',
    '.dccccccccccd.',
    '.dddddddddddd.',
  ] },
  values_mug: { rows: [
    '.....s.s......',
    '......s.s.....',
    '..WWWWWWWWV...',
    '..WWWWWWWWVbb.',
    '..WWBBBBWWVb.b',
    '..WBBlBBBBVb.b',
    '..WWBBBBWWVb.b',
    '..WWWWWWWWVb.b',
    '..WWWWWWWWVbb.',
    '...VVVVVVVV...',
  ] },
  sick_note: { rows: [
    '.WWWWWWWWWWW..',
    '.WVVVVVVVVVW..',
    '.WWWWWWWWWWW..',
    '.WVVVVVWWWRW..',
    '.WWWWWWWWRRRr.',
    '.WVVVVVVWWRW..',
    '.WWWWWWWWWWW..',
    '.WVVVVVVVVWW..',
    '.WWWWWWWWWWW..',
    '.VVVVVVVVVVv..',
  ] },
  hands_free_headset: { rows: [
    '....dddddd....',
    '..dd......dd..',
    '.dd........dd.',
    '.d..........d.',
    '.d..........d.',
    'dcd........dcd',
    'dcd........dcd',
    'dcd........dcd',
    '.dd.......dd..',
    '..........d...',
    '.........d....',
    '........Rd....',
  ] },
  parking_permit: { rows: [
    '.....bbbb.....',
    '....b....b....',
    '....b....b....',
    '..jjjjjjjjjj..',
    '..jBBBBBBBBj..',
    '..jBWWWWWBBj..',
    '..jBWBBBBWBj..',
    '..jBWWWWWBBj..',
    '..jBWBBBBBBj..',
    '..jBWBBBBBBj..',
    '..jBBBBBBBBj..',
    '..jjjjjjjjjj..',
  ] },
  confiscated_whistle: { rows: build(14, 14, (p, rc, dc, ln) => {
    rc(0, 7, 5, 3, 'b'); rc(0, 7, 5, 1, 'a'); rc(0, 9, 5, 1, 'c'); p(0, 7, 'w');
    rc(4, 5, 8, 6, 'b'); rc(4, 5, 8, 1, 'a'); rc(4, 10, 8, 1, 'c'); rc(11, 5, 1, 6, 'c'); p(4, 5, 'w'); p(11, 5, '.'); p(11, 10, '.');
    rc(6, 5, 3, 1, 'e'); rc(6, 6, 3, 1, 'd'); rc(5, 7, 1, 2, 'a');
    ln(12, 6, 13, 7, 'c', 1); p(13, 8, 'c'); p(12, 9, 'c');
    ln(13, 9, 11, 13, 'R', 1); p(12, 13, 'q');
  }) },
  hr_complaint: { rows: [
    '.WWWWWWWWWWW..',
    '.WRRRRRRRRRW..',
    '.WWWWWWWWWWW..',
    '.WdWddddddWW..',
    '.WWWWWWWWWWW..',
    '.WdWddddddWW..',
    '.WWWWWWWWWWW..',
    '.WdWRRRRRWWW..',
    '.WWWWWWWWWWW..',
    '.VVVVVVVVVVv..',
  ] },
  visitor_pass: { rows: [
    '.....bbbb.....',
    '.....bccb.....',
    '..WWWWWWWWWW..',
    '..WGGGGGGGGV..',
    '..WGwwwwwwGV..',
    '..WGGGGGGGGV..',
    '..WWWWWWWWWV..',
    '..WWdddddWWV..',
    '..WWWWWWWWWV..',
    '..WWdddWWWWV..',
    '..VVVVVVVVVv..',
  ] },
  rubber_duck: { rows: [
    '......YYY.....',
    '.....YyYYY....',
    '.....YYdYYOO..',
    '.....YYYYOOo..',
    '.....YYYY.....',
    '..Y..YYYY.....',
    '.YYY.YYYYY....',
    'YYYYYYYYYYYY..',
    'YYYYYYYYYYYYu.',
    'YyYYYYYYYYYuu.',
    '.YYYYYYYYYuu..',
    '..uuuuuuuuu...',
  ], pal: { Y: '#f6cf3c', y: '#fff0a0', u: '#c58f1c' } },
};

export const DESK_FALLBACK: IDef = { rows: [
  '..............',
  '..TTTTTTTTTT..',
  '.tTTTTTTTTTTm.',
  '.TTTTTTTTTTTm.',
  '.TTTTTWWTTTTm.',
  '.TTTTWTTWTTTm.',
  '.TTTTTTTWTTTm.',
  '.TTTTTTWTTTTm.',
  '.TTTTTTTTTTTm.',
  '.TTTTTTWTTTTm.',
  '.mmmmmmmmmmmm.',
] };
