// HUD + policy icons.
import type { IconName } from '../items';
import type { IDef } from './gfx';
import { build } from './gfx';

/** Overlay a red prohibition sign (ring + slash) on a small glyph, centred in a 14x14 grid on a pale disc. */
function prohibit(glyph: string[]): string[] {
  const N = 14;
  const grid: string[][] = Array.from({ length: N }, () => Array(N).fill('.'));
  const gw = Math.max(...glyph.map((r) => r.length));
  const ox = Math.floor((N - gw) / 2), oy = Math.floor((N - glyph.length) / 2);
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const dx = x + 0.5 - 7, dy = y + 0.5 - 7;
    if (dx * dx + dy * dy <= 5.4 * 5.4) grid[y][x] = 'W';
  }
  glyph.forEach((row, y) => { for (let x = 0; x < row.length; x++) if (row[x] !== '.') grid[oy + y][ox + x] = row[x]; });
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const dx = x + 0.5 - 7, dy = y + 0.5 - 7, d = Math.sqrt(dx * dx + dy * dy);
    const ring = d > 5.3 && d <= 7;
    const slash = d <= 6.2 && Math.abs(dx - dy) < 1.05;
    if (ring) grid[y][x] = d > 6.4 ? 'q' : 'R';
    else if (slash) grid[y][x] = 'R';
  }
  return grid.map((r) => r.join(''));
}

export const ICONS_HUD: Partial<Record<IconName, IDef>> = {
  hp: { rows: [
    '..............',
    '..rrr....rrr..',
    '.rwRRr..rRRRr.',
    '.rwRRRrrRRRRR.',
    '.RRRRRRRRRRRq.',
    '.RRRRRRRRRRRq.',
    '..RRRRRRRRRq..',
    '...RRRRRRRq...',
    '....RRRRRq....',
    '.....RRRq.....',
    '......Rq......',
  ] },
  shield: { rows: [
    '.jjjjjjjjjjjj.',
    '.jllBBBBBBBBj.',
    '.jlBBBBBBBBBj.',
    '.jBBBBBBBBBBj.',
    '.jBBBBBBBBBBj.',
    '.jBBBBBBBBBBj.',
    '..jBBBBBBBBj..',
    '..jBBBBBBBBj..',
    '...jBBBBBBj...',
    '....jBBBBj....',
    '.....jjjj.....',
  ] },
  rage: { rows: [
    '.......r......',
    '......rR......',
    '.....rRR..r...',
    '....rRRR.rR...',
    '...rRROORRRR..',
    '..rRROOooORRq.',
    '..RROOooooORq.',
    '.RROOoyyyOORRq',
    '.RROOyyyyoORRq',
    '.RROOoyyyOORq.',
    '..RROOOOOORq..',
    '...qRRRRRRq...',
    '.....qqqq.....',
  ] },
  cash: { rows: [
    '....uuuuuu....',
    '..uuYyyYYYuu..',
    '.uYYYYuuYYYYu.',
    '.uYYYuYYYYYYu.',
    'uYYYYuYYYYYYYu',
    'uYYYuuuuYYYYYu',
    'uYYYYuYYYYYYYu',
    'uYYYuYYYYuYYYu',
    '.uYuuuuuuuYYu.',
    '.uYYYYYYYYYYu.',
    '..uuYYYYYYuu..',
    '....uuuuuu....',
  ] },
  leave: { rows: [
    '....hhhhhh....',
    '..hhGggGGGhh..',
    '.hGGGGYGGGGGh.',
    '.hGGYGYGYGGGh.',
    'hGGGGYYYYGGGGh',
    'hGGYYYYYYYYGGh',
    'hGGGGYYYYGGGGh',
    'hGGYGYGYGYGGGh',
    '.hGGGGYGGGGGh.',
    '.hGGGGGGGGGGh.',
    '..hhGGGGGGhh..',
    '....hhhhhh....',
  ] },
  ammo: { rows: [
    '..............',
    '..Y..Y..Y.....',
    '.YyY.YyY.YyY..',
    '.YYY.YYY.YYY..',
    '.YYY.YYY.YYY..',
    '.YYu.YYu.YYu..',
    '.uuu.uuu.uuu..',
    '.bbb.bbb.bbb..',
    '.bcc.bcc.bcc..',
    '.ddd.ddd.ddd..',
  ] },
  durability: { rows: [
    '..............',
    '.bbbbbbbbbbb..',
    'baaaaaaaaaabc.',
    'bbbbbbdbbbbbc.',
    'bbbbbbdddbbbc.',
    'bcccccccdcccc.',
    '.dddddddcdddd.',
    '.....mTt.d....',
    '.....mTt......',
    '.....mTt......',
    '.....mTt......',
    '.....mTt......',
    '.....NmN......',
  ] },
  skull: { rows: [
    '..............',
    '...wwwwwwww...',
    '..wWWWWWWWWV..',
    '.wWWWWWWWWWWV.',
    '.WWeeeWWeeeWV.',
    '.WWeeeWWeeeWV.',
    '.WWeeWddWeeWV.',
    '..WWWWddWWWV..',
    '...WWWWWWWV...',
    '...WdWdWdWV...',
    '...VVVVVVVv...',
  ] },
  lock: { rows: [
    '....bbbbbb....',
    '...bwaaaaab...',
    '...bc....cb...',
    '...bc....cb...',
    '.YYYYYYYYYYYu.',
    '.YyyyYYYYYYYu.',
    '.YyYYYddYYYYu.',
    '.YYYYYddYYYYu.',
    '.YYYYYdYYYYYu.',
    '.YYYYYYYYYYYu.',
    '.uuuuuuuuuuuu.',
  ] },
  unlock: { rows: [
    '.....bbbbbb...',
    '....bwaaaaab..',
    '....bc....cb..',
    '....bc........',
    '.YYYYYYYYYYYu.',
    '.YyyyYYYYYYYu.',
    '.YyYYYddYYYYu.',
    '.YYYYYddYYYYu.',
    '.YYYYYdYYYYYu.',
    '.YYYYYYYYYYYu.',
    '.uuuuuuuuuuuu.',
  ] },
  star: { rows: [
    '......yY......',
    '......YY......',
    '.....yYYu.....',
    'yyyyyYYYYYYuuu',
    '.yYYYYYYYYYYu.',
    '..uYYYYYYYYu..',
    '...uYYYYYYu...',
    '...YYYYYYYYu..',
    '..YYYYuuYYYYu.',
    '..YYYu..uYYYu.',
    '.uYu......uYu.',
  ] },
  kpi: { rows: [
    '.........ggh..',
    '.........GGh..',
    '.........GGh..',
    '.........GGh..',
    '.....zzh.GGh..',
    '.....ZZh.GGh..',
    '.....ZZh.GGh..',
    '.llj.ZZh.GGh..',
    '.BBj.ZZh.GGh..',
    '.BBj.ZZh.GGh..',
    'dddddddddddddd',
  ] },
  clock: { rows: [
    '....dddddd....',
    '..ddWWWWWWdd..',
    '.dWWWWdWWWWWd.',
    '.dWWWWdWWWWWd.',
    'dWWWWWdWWWWWWd',
    'dWdWWWdddWWdWd',
    'dWWWWWWWWWWWWd',
    'dWWWWWWWWWWWWd',
    '.dWWWWdWWWWWd.',
    '.dWWWWWWWWWVd.',
    '..ddVVVVVVdd..',
    '....dddddd....',
  ] },
  stairs: { rows: build(14, 14, (p, rc) => {
    for (let x = 1; x <= 12; x++) {
      const h = 2 + 3 * Math.floor((x - 1) / 3);
      for (let y = 13 - h; y <= 12; y++) p(x, y, y === 13 - h ? 'w' : (x - 1) % 3 === 0 && x > 1 ? 'a' : y > 10 ? 'c' : 'b');
      p(x, 13, 'd');
    }
    for (let x = 1; x <= 12; x++) p(x, 13, 'd');
  }) },
  lift: { rows: [
    '.dddddddddddd.',
    '.deeeeeeeeeed.',
    '.deeeYYeeGGed.',
    '.deeYYYYeGGed.',
    '.dddddddddddd.',
    '.dabbbbdbbbcd.',
    '.dabbbbdbbbcd.',
    '.dabbbbdbbbcd.',
    '.dabbbbdbbbcd.',
    '.dabbbbdbbbcd.',
    '.dddddddddddd.',
  ] },
  corridor: { rows: build(14, 12, (p, rc) => {
    for (let y = 0; y < 12; y++) for (let x = 0; x < 14; x++) {
      const u = x + 0.5 - 7, v = y + 0.5 - 5.5;
      const back = Math.abs(u) <= 2.5 && Math.abs(v) <= 2.5;
      if (back) { p(x, y, 'T'); continue; }
      const wall = Math.abs(u) / 7 > Math.abs(v) / 5.5;
      p(x, y, wall ? (u < 0 ? 'b' : 'c') : (v < 0 ? 'd' : 'a'));
    }
    rc(4, 3, 6, 1, 'm'); rc(4, 3, 1, 5, 'm'); rc(9, 3, 1, 5, 'm'); rc(5, 4, 4, 3, 'Y'); rc(5, 4, 4, 1, 'y'); rc(6, 7, 2, 1, 'N');
    rc(0, 0, 14, 1, 'e'); rc(0, 11, 14, 1, 'd');
  }) },
  grab: { rows: [
    '....F.F.F.....',
    '...FfFFfFF....',
    '...FfFFfFFF...',
    '.F.FFFFFFFFF..',
    '.FfFFFFFFFFFs.',
    '.FFFFFFFFFFs..',
    '..FFFFFFFFFs..',
    '..sFFFFFFFs...',
    '...sFFFFFss...',
    '....WWWWWV....',
    '....WWWWWV....',
  ] },
  interact: { rows: [
    '.....FF.......',
    '....FffF......',
    '....FfFF......',
    '....FfFFFFF...',
    '....FfFFFFFFF.',
    '.FF.FFFFFFFFs.',
    '.FFFFFFFFFFFs.',
    '..FFFFFFFFFs..',
    '..sFFFFFFFs...',
    '...sFFFFFs....',
    '....WWWWWV....',
  ] },
  execution: { rows: [
    '.dd........dd.',
    '.dd.bbbbbb.dd.',
    '.dd.baaaab.dd.',
    '.dd.bbbbbb.dd.',
    '.dd.cbbbbc.dd.',
    '.dd..cbbc..dd.',
    '.dd...RR...dd.',
    '.dd...Rq...dd.',
    '.dd........dd.',
    '.TTTTTTTTTTTT.',
    '.mmmmmmmmmmmm.',
  ] },
  window: { rows: [
    '.bbbbbbbbbbbb.',
    '.bllllBlllllb.',
    '.blwlllBllllb.',
    '.bllllllBlllb.',
    '.bBBBBBBBBBBb.',
    '.bllllBlllllb.',
    '.bllllBlllllb.',
    '.bllllBlllllb.',
    '.bbbbbbbbbbbb.',
    '.cccccccccccc.',
  ] },
  promotion: { rows: [
    '......Y.......',
    '.....YYY......',
    '....YyYYY.....',
    '...YyYYYYY....',
    '..YyYYYYYYY...',
    '.uuuuYYYuuuu..',
    '....uYYYu.....',
    '....uYYYu.....',
    '....uYYYu.....',
    '....uuuuu.....',
    '.GGGGGGGGGGG..',
    '.hhhhhhhhhhh..',
  ] },
  trophy: { rows: [
    '..............',
    '.uYYYYYYYYYYu.',
    'uYuYyYYYYYYuYu',
    'YuuYyYYYYYYuuY',
    'YuuYYYYYYYYuuY',
    '.uYuYYYYYYuYu.',
    '...uuYYYYuu...',
    '.....uYYu.....',
    '.....uYYu.....',
    '....uuYYuu....',
    '...uYYYYYYu...',
    '...uuuuuuuu...',
  ] },
  seed: { rows: [
    '..............',
    '......gg..gg..',
    '.....gGGggGGh.',
    '....gGGGGGGGh.',
    '.....hGGhGGh..',
    '......hGGh....',
    '.......GG.....',
    '.......Gh.....',
    '..mmmmmGhmmm..',
    '.mTTTTTmmTTTm.',
    '.NmmmmmmmmmNN.',
  ] },
  daily: { rows: [
    '.bb........bb.',
    '.bbbbbbbbbbbb.',
    '.RRRRRRRRRRRR.',
    '.RrRRRRRRRRRq.',
    '.WWWWWWWWWWWV.',
    '.WWWWWYYWWWWV.',
    '.WWWWYyYYWWWV.',
    '.WWWYyYYYYWWV.',
    '.WWWWYYYYWWWV.',
    '.WWWWWYYWWWWV.',
    '.VVVVVVVVVVVv.',
  ] },
  email: { rows: [
    '..............',
    '.wWWWWWWWWWWV.',
    '.WVWWWWWWWWVV.',
    '.WWVWWWWWWVWV.',
    '.WWWVWWWWVWWV.',
    '.WWWWVVVVWWWV.',
    '.WWWWWWWWWWWV.',
    '.WWWWWWWWWWWV.',
    '.VVVVVVVVVVVv.',
  ] },
  attachment: { rows: [
    '....bbbbb.....',
    '...bwaaaab....',
    '..bwb...bab...',
    '..bab.bb.cb...',
    '..bab.bcb.b...',
    '..bab.bcb.b...',
    '..bab.bcb.b...',
    '..bab.bcb.b...',
    '..bab.bcb.b...',
    '..bcb.bcb.b...',
    '...bcbbcb.....',
    '....bbbb......',
  ] },
  warning: { rows: [
    '......YY......',
    '.....YyYY.....',
    '.....YddY.....',
    '....YYddYY....',
    '....YYddYY....',
    '...YYYddYYY...',
    '...YYYddYYY...',
    '..YYYYYYYYYY..',
    '..YYYYddYYYY..',
    '.YYYYYddYYYYu.',
    '.uuuuuuuuuuuu.',
  ] },
  info: { rows: [
    '....jjjjjj....',
    '..jjBllBBBjj..',
    '.jBBBBWWBBBBj.',
    '.jBBBBWWBBBBj.',
    'jBBBBBBBBBBBBj',
    'jBBBBWWWBBBBBj',
    'jBBBBBWWBBBBBj',
    'jBBBBBWWBBBBBj',
    '.jBBBWWWWBBBj.',
    '.jBBBBBBBBBBj.',
    '..jjBBBBBBjj..',
    '....jjjjjj....',
  ] },
  check: { rows: [
    '..............',
    '..........gg..',
    '.........gGGh.',
    '........gGGh..',
    '.......gGGh...',
    '..gg..gGGh....',
    '.gGGggGGh.....',
    '..gGGGGh......',
    '...gGGh.......',
    '....Gh........',
  ] },
  cross: { rows: [
    '..............',
    '.rR........Rr.',
    '.RRR......RRq.',
    '..RRR....RRq..',
    '...RRR..RRq...',
    '....RRRRRq....',
    '.....RRRq.....',
    '....RRRRRq....',
    '...RRR.RRRq...',
    '..RRR...RRRq..',
    '.RRq.....qRRq.',
  ] },
  gear: { rows: [
    '.....bbbb.....',
    '..bb.baab.bb..',
    '.bbbbbaabbbbb.',
    '..bbbbbbbbbb..',
    '..bbbdddddbb..',
    'bbbbdccccdbbbb',
    'abbbdc..cdbbbc',
    'bbbbdccccdbbbb',
    '..bbbdddddbbc.',
    '..bbbbbbbbbc..',
    '.bbbbbccbbbcc.',
    '..cc.bccb.cc..',
    '.....cccc.....',
  ] },
  radio: { rows: [
    '.........d....',
    '.........d....',
    '.dddddddddd...',
    '.dccccccccd...',
    '.dcGGGGGGcd...',
    '.dcGgGGGGcd...',
    '.dccccccccd...',
    '.dcdcdcdcdd...',
    '.dcccccccd....',
    '.dcdcdcdcd....',
    '.dccccccccd...',
    '.dddddddddd...',
  ] },
  car: { rows: [
    '..............',
    '....bbbbbb....',
    '...bwlllllbb..',
    '..bwlllbllllb.',
    '.RRRRRRRRRRRRq',
    'RrRRRRRRRRRRRq',
    'RRRRRRRRRRRRYq',
    'qqqqqqqqqqqqqq',
    '.eeee....eeee.',
    '.ecce....ecce.',
    '..ee......ee..',
  ] },
  noticeboard: { rows: [
    'TTTTTTTTTTTTTT',
    'TyYYYYYYYYYYYT',
    'TYWWWYYWWWYYYT',
    'TYWRWYYWVWYYYT',
    'TYWWWYYWWWYWWT',
    'TYYYYYYYYYYWVT',
    'TYYWWWWYYYYWWT',
    'TYYWVVWYYYYYYT',
    'TYYWWWWYYYYYYT',
    'TYYYYYYYYYYYYT',
    'mmmmmmmmmmmmmm',
  ] },
  vending: { rows: [
    '.dddddddddddd.',
    '.dbbbbbbbbbcd.',
    '.dblBlBlBblcd.',
    '.dbRYGRYGbbcd.',
    '.dbbbbbbbbbcd.',
    '.dbOPBOPBbbcd.',
    '.dbbbbbbbbbcd.',
    '.dbbbbbbbbbcd.',
    '.dcccccccccdd.',
    '.dcdddddddcdd.',
    '.dcdeeeeedcdd.',
    '.dddddddddddd.',
  ] },
  boot: { rows: [
    '..............',
    '..NNNN........',
    '..NmmN........',
    '..NmTN........',
    '..NmTN........',
    '..NmTNN.......',
    '..NmTTTNN.....',
    '.NmTTTTTTNNN..',
    '.NmTTTTTTTTmN.',
    '.NNNNNNNNNNNN.',
    '.eeeeeeeeeeee.',
  ] },
  dashboard: { rows: [
    '.dddddddddddd.',
    '.dZZZZZZZZZZd.',
    '.dZwwwZZZZZZd.',
    '.dZwZZZZZZZZd.',
    '.dZwZZZWZZZZd.',
    '.dZZZZZWZZZZd.',
    '.dZZZZZZWZZZd.',
    '.dZZGGZZZRRZd.',
    '.dZZZZZZZZZZd.',
    '.dddddddddddd.',
  ] },
  policy_no_dash: { rows: prohibit([
    'BB..BB..',
    '.BB..BB.',
    '..BB..BB',
    '.BB..BB.',
    'BB..BB..',
  ]) },
  policy_no_ranged: { rows: prohibit([
    '...YY...',
    '..YyYY..',
    '..YYYY..',
    '..YYYY..',
    '..uuuu..',
    '.dddddd.',
    '.dccccd.',
    '.dddddd.',
  ]) },
  policy_no_rage: { rows: prohibit([
    '...O....',
    '..OO.O..',
    '.OOOOO..',
    '.OoOOOO.',
    '.OOyOOO.',
    '.OOOOOO.',
    '..OOOO..',
  ]) },
  policy_no_grab: { rows: prohibit([
    '.F.F.F..',
    'FfFFfFF.',
    'FFFFFFF.',
    'FFFFFFFs',
    '.FFFFFs.',
    '..FFFs..',
    '..WWW...',
  ]) },
  policy_no_melee: { rows: prohibit([
    '......bb',
    '.....bbc',
    '....bbc.',
    '...bbc..',
    '..TTc...',
    '.TTc....',
    '.Tm.....',
  ]) },
};
